# Generated by Django 4.1.1 on 2022-10-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eccomapp', '0004_remove_profile_user_alter_profile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomapp.customer'),
        ),
    ]
